/*
 * This Scala source file was generated by the Gradle 'init' task.
 */

import javafx.animation.Animation
import javafx.animation.Interpolator
import javafx.animation.PathTransition
import javafx.application.Application
import javafx.scene.Group
import javafx.scene.Scene
import javafx.scene.paint.Color
import javafx.scene.shape.Circle
import javafx.stage.Stage
import javafx.util.Duration

object Animation01 extends App {
    Application.launch(args: _*);
}

class Animation01() extends Application {
    override def start(primaryStage: Stage): Unit = {
        val root = new Group

        val aCircle = new Circle(100)
        aCircle.setFill(null)
        aCircle.setStroke(Color.BLUE)
        aCircle.setLayoutX(200)
        aCircle.setLayoutY(200)
        aCircle.setOpacity(0.5)
        root.getChildren.add(aCircle)

        val redCircle = new Circle(5)
        redCircle.setFill(Color.RED)
        redCircle.setStroke(Color.WHITE)
        root.getChildren.add(redCircle)

        val pt = new PathTransition()
        pt.setNode(redCircle)
        pt.setDuration(Duration.millis(5000))
        pt.setPath(aCircle)
        pt.setInterpolator(Interpolator.LINEAR)
        pt.setCycleCount(Animation.INDEFINITE)

        val aScene = new Scene(root, 400, 400)

        primaryStage.setScene(aScene)
        primaryStage.show

        pt.play
    }
}
